table 'EUROSTAT - Datos Macro'
	lineageTag: 3fdaa40d-69d7-4869-8c0a-9d3760a59af4

	measure 'Métrica seleccionada EUROSTAT' =
			VAR _sel = SELECTEDVALUE('Selector métrica EUROSTAT'[Parámetro Orden])
			RETURN
			SWITCH(
			    _sel,
			    0, AVERAGE('EUROSTAT - Datos Macro'[Num Empresas]),
			    1, AVERAGE('EUROSTAT - Datos Macro'[Facturación €]),
			    2, AVERAGE('EUROSTAT - Datos Macro'[Valor Producción €]),
			    3, AVERAGE('EUROSTAT - Datos Macro'[Margen Bruto €]),
			    4, AVERAGE('EUROSTAT - Datos Macro'[Valor Añadido €])
			)
		lineageTag: e5f6a7b8-c9d0-1234-efab-345678901234

	column 'Región Mercado'
		dataType: string
		lineageTag: 5ad3ee35-550e-4a5d-a6e6-a159ad900934
		summarizeBy: none
		sourceColumn: Región Mercado

		annotation SummarizationSetBy = Automatic

	column País
		dataType: string
		lineageTag: ccb4ab5a-5fc9-4828-8796-f04f1398fb8a
		summarizeBy: none
		sourceColumn: País

		annotation SummarizationSetBy = Automatic

	column Año
		dataType: int64
		formatString: 0
		lineageTag: 3d641b75-81d7-4cd2-8814-1ea0178150ed
		summarizeBy: none
		sourceColumn: Año

		annotation SummarizationSetBy = User

	column 'Num Empresas'
		dataType: int64
		formatString: #,##0
		lineageTag: d011b321-cf4f-4b28-8532-b382b78961a6
		summarizeBy: average
		sourceColumn: Num Empresas

		annotation SummarizationSetBy = User

	column 'Facturación €'
		dataType: double
		formatString: #,##0
		lineageTag: 5196406d-4656-474e-9901-63784798aa47
		summarizeBy: average
		sourceColumn: Facturación €

		annotation SummarizationSetBy = User

	column 'Valor Producción €'
		dataType: double
		formatString: #,##0
		lineageTag: 2622457b-8198-4c3d-8cbd-6e20d776d342
		summarizeBy: average
		sourceColumn: Valor Producción €

		annotation SummarizationSetBy = User

	column 'Margen Bruto €'
		dataType: double
		formatString: #,##0
		lineageTag: 3fedd7c1-5909-4080-bd03-a4f34618155c
		summarizeBy: average
		sourceColumn: Margen Bruto €

		annotation SummarizationSetBy = User

	column 'Valor Añadido €'
		dataType: double
		formatString: #,##0
		lineageTag: c8ae99e2-26db-4165-9ebc-49aa048846fc
		summarizeBy: average
		sourceColumn: Valor Añadido €

		annotation SummarizationSetBy = User

	partition 'EUROSTAT - Datos Macro' = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\rodri\Documents\Proyectos\Personal\proyecto-ade-gema\Datos-Tratados\EUROSTAT.xlsx"), null, true),
				    #"Datos finales_Sheet" = Origen{[Item="Datos finales",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(#"Datos finales_Sheet", [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos", {
				        {"Región Mercado", type text},
				        {"País", type text},
				        {"Año", Int64.Type},
				        {"Num Empresas", Int64.Type},
				        {"Facturación €", type number},
				        {"Valor Producción €", type number},
				        {"Margen Bruto €", type number},
				        {"Valor Añadido €", type number}
				    })
				in
				    #"Tipo cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

