table 'EUROSTAT - Datos Macro'
	lineageTag: 3fdaa40d-69d7-4869-8c0a-9d3760a59af4

	column 'Región Mercado'
		dataType: string
		lineageTag: 5ad3ee35-550e-4a5d-a6e6-a159ad900934
		summarizeBy: none
		sourceColumn: Región Mercado

		annotation SummarizationSetBy = Automatic

	column País
		dataType: string
		lineageTag: ccb4ab5a-5fc9-4828-8796-f04f1398fb8a
		summarizeBy: none
		sourceColumn: País

		annotation SummarizationSetBy = Automatic

	column Año
		dataType: string
		lineageTag: 3d641b75-81d7-4cd2-8814-1ea0178150ed
		summarizeBy: none
		sourceColumn: Año

		annotation SummarizationSetBy = Automatic

	column 'Num Empresas'
		dataType: string
		lineageTag: d011b321-cf4f-4b28-8532-b382b78961a6
		summarizeBy: none
		sourceColumn: Num Empresas

		annotation SummarizationSetBy = Automatic

	column 'Facturación €'
		dataType: string
		lineageTag: 5196406d-4656-474e-9901-63784798aa47
		summarizeBy: none
		sourceColumn: Facturación €

		annotation SummarizationSetBy = Automatic

	column 'Valor Producción €'
		dataType: string
		lineageTag: 2622457b-8198-4c3d-8cbd-6e20d776d342
		summarizeBy: none
		sourceColumn: Valor Producción €

		annotation SummarizationSetBy = Automatic

	column 'Margen Bruto €'
		dataType: string
		lineageTag: 3fedd7c1-5909-4080-bd03-a4f34618155c
		summarizeBy: none
		sourceColumn: Margen Bruto €

		annotation SummarizationSetBy = Automatic

	column 'Valor Añadido €'
		dataType: string
		lineageTag: c8ae99e2-26db-4165-9ebc-49aa048846fc
		summarizeBy: none
		sourceColumn: Valor Añadido €

		annotation SummarizationSetBy = Automatic

	partition 'EUROSTAT - Datos Macro' = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\rodri\Documents\Proyectos\Personal\proyecto-ade-gema\Datos-Tratados\EUROSTAT.xlsx"), null, true),
				    #"Datos finales_Sheet" = Origen{[Item="Datos finales",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(#"Datos finales_Sheet", [PromoteAllScalars=true])
				in
				    #"Encabezados promovidos"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

