table 'SABI - Empresas competidores Españolas'
	lineageTag: 84c2aeff-1773-4881-ac83-73d7555573e8

	column Año
		dataType: string
		lineageTag: 79b3b920-5e10-4a08-aab1-c3b11a0c488d
		summarizeBy: none
		sourceColumn: Año

		annotation SummarizationSetBy = Automatic

	column 'ID Empresa'
		dataType: string
		lineageTag: b83e50c6-78c8-4abd-895d-d06c22306c90
		summarizeBy: none
		sourceColumn: ID Empresa

		annotation SummarizationSetBy = Automatic

	column Nombre
		dataType: string
		lineageTag: 8a23e6ba-c77e-4ab0-a627-109f65704bd5
		summarizeBy: none
		sourceColumn: Nombre

		annotation SummarizationSetBy = Automatic

	column Ciudad
		dataType: string
		lineageTag: 6183026a-aa93-4564-a8d4-cd2a1c80313c
		summarizeBy: none
		sourceColumn: Ciudad

		annotation SummarizationSetBy = Automatic

	column Tipo
		dataType: string
		lineageTag: f3b8ea71-7fe1-4e3b-ac8b-95768481f6ad
		summarizeBy: none
		sourceColumn: Tipo

		annotation SummarizationSetBy = Automatic

	column 'Cierre Fiscal'
		dataType: string
		lineageTag: 364a0b3b-fe6e-453a-bc18-8f4f9a10cc65
		summarizeBy: none
		sourceColumn: Cierre Fiscal

		annotation SummarizationSetBy = Automatic

	column 'Fecha Cierre'
		dataType: string
		lineageTag: 933c0b97-0cbc-4a51-b01e-c84d8b1bcad2
		summarizeBy: none
		sourceColumn: Fecha Cierre

		annotation SummarizationSetBy = Automatic

	column Ingresos
		dataType: string
		lineageTag: 003ee89c-7741-4f64-b90d-b97d39b83d91
		summarizeBy: none
		sourceColumn: Ingresos

		annotation SummarizationSetBy = Automatic

	column 'Resultados ant impuestos'
		dataType: string
		lineageTag: 88121cfa-dbc3-4897-979c-db5e3b20a8d2
		summarizeBy: none
		sourceColumn: Resultados ant impuestos

		annotation SummarizationSetBy = Automatic

	column 'Resultado Neto'
		dataType: string
		lineageTag: 8ff1d45e-267f-4989-8daa-248cada12b5b
		summarizeBy: none
		sourceColumn: Resultado Neto

		annotation SummarizationSetBy = Automatic

	column 'Activo Total'
		dataType: string
		lineageTag: 2c6cbce7-8d70-458f-bd13-76f494102de2
		summarizeBy: none
		sourceColumn: Activo Total

		annotation SummarizationSetBy = Automatic

	column 'Fondos Propios'
		dataType: string
		lineageTag: abfb3b1c-4720-47ce-9040-56c2fe3d51ae
		summarizeBy: none
		sourceColumn: Fondos Propios

		annotation SummarizationSetBy = Automatic

	column 'ROI pct'
		dataType: string
		lineageTag: 81f282cf-70ea-4114-956b-fda8735f6275
		summarizeBy: none
		sourceColumn: ROI pct

		annotation SummarizationSetBy = Automatic

	column 'ROE pct'
		dataType: string
		lineageTag: 2f39d445-0ff8-4ad4-bef0-d304a4de0f1a
		summarizeBy: none
		sourceColumn: ROE pct

		annotation SummarizationSetBy = Automatic

	column Liquidez
		dataType: string
		lineageTag: 154fbec0-a3d3-45aa-8464-48d3679f7488
		summarizeBy: none
		sourceColumn: Liquidez

		annotation SummarizationSetBy = Automatic

	column 'Endeudamiento Porcentual'
		dataType: string
		lineageTag: 0584a6f7-dc65-438e-8302-be8e23d27056
		summarizeBy: none
		sourceColumn: Endeudamiento Porcentual

		annotation SummarizationSetBy = Automatic

	column Empleados
		dataType: string
		lineageTag: 99a25e7c-1e5c-47d8-b8b0-6f5c2d5abc9c
		summarizeBy: none
		sourceColumn: Empleados

		annotation SummarizationSetBy = Automatic

	partition 'SABI - Empresas competidores Españolas' = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\rodri\Documents\Proyectos\Personal\proyecto-ade-gema\Datos-Tratados\SABI.xlsx"), null, true),
				    #"Datos finales_Sheet" = Origen{[Item="Datos finales",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos1" = Table.PromoteHeaders(#"Datos finales_Sheet", [PromoteAllScalars=true])
				in
				    #"Encabezados promovidos1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

